### PR TITLE
Feat/typings support

### PR DESCRIPTION
**Pull request by zentby**

### CODE REVIEW

**Comment by nutboltu** [comment]
@zentby we need to add the types in the package.json file.

```
"types": "index.d.ts"
```

**Review by nutboltu — CHANGES_REQUESTED** [review]
@zentby we need to add the types in the package.json file.

```
"types": "index.d.ts"
```

**Comment by zentby** [comment]
@nutboltu thanks for reviewing. Updated with suggested.

**Review by nutboltu — APPROVED** [review]
LGTM @zentby. thanks for the contribution! 🥇

**Pull request merged**
